### ISSUE TITLE
i can't open the hack

### ISSUE THREAD

**Issue by tarcisomoraes** [SarnaxLii/Valorant-Hack#5]
hi brother, I'm new to the community, I downloaded the visual studio but not understanding how to use the hack, could you make a video explaining? other people may have that same doubt

**Comment by tarcisomoraes** [comment]
how do i search on google?

**Comment by SarnaxLii** [comment]
https://stackoverflow.com/questions/19287273/c-how-to-create-an-executable-out-of-my-program

**Comment by tarcisomoraes** [comment]
thanks
