### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tarcisomoraes** [SarnaxLii/Valorant-Hack#6]

**Comment by SarnaxLii** [comment]
what is problem ?

**Comment by SarnaxLiiFanN1** [comment]
HII sorry for the inconvenience but could you give me a mini tutorial on how to use it? Greetings from Argentina

**Comment by SarnaxLii** [comment]
You need to write an additional src to make it work ( Seach google Valorant esp src ) and compile it to .exe .

**Comment by seanraaf2** [comment]
how to use spoofer valorant bro?, thanks in advance

**Comment by SarnaxLii** [comment]
google bro , i dont no Teacher

**Comment by CHN1008** [comment]
its virus

**Comment by CHN1008** [comment]
not a sln file. its a nls..exe fake virus file

**Comment by SarnaxLiiFanN1** [comment]
It is NOT a virus but it is a bit difficult to make it work without a tutorial

**Comment by CHN1008** [comment]
then could you show me tutorial?

**Comment by CHN1008** [comment]
i just wanna use spoofer file , but there is no sln file . it can't be complied

**Comment by seanraaf2** [comment]
its virus?

**Comment by CHN1008** [comment]
> its virus?

i think. because there is no solution file in these folder , also it's exe file.

**Comment by SarnaxLii** [comment]
lol this joke
