### ISSUE TITLE
Which file do I open?

### ISSUE THREAD

**Issue by raindropswish1** [SarnaxLii/Valorant-Hack#9]
I have Visual Studio installed and everything needed it seems but I cant find which Visual Studio file I need to run. Whenever I run "ValorantAimbot.snl" I always get an error that says, "One or more projects in the solution were not loaded correctly". Maybe I'm opening the wrong file so I thought I may as well ask which I open.
![image](https://user-images.githubusercontent.com/73418833/148493203-aff23b00-8df2-4ef1-a748-5a66f6095b1d.png)

**Comment by SarnaxLii** [comment]
I've been having this problem a lot. It is currently being edited and the next release is January 14th and I will make it an External .exe available.

**Comment by SarnaxLiiFanN1** [comment]
The same thing happens to me, there is no solution?
 :c

**Comment by SarnaxLii** [comment]
I do not understand what you are asking

**Comment by SarnaxLiiFanN1** [comment]
About this error
![error](https://user-images.githubusercontent.com/97271283/148605921-2e5fc0dd-3500-4d49-9d2b-05030a8a84c2.png)
